test:ubuntu-trusty:
  image: nitemv/ubuntu-trusty
  script:
    - apt-get install -y php5-cli curl facter
    - curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/bin
    - composer install
    - php bin/test.php storage/nginx.law.php commit
    - sleep 5 # allow nginx to settle down
    - diff <(curl -Ss http://localhost/) <(echo -n "success:order")
test:void:
  image: eater/void-order
  script:
    - sed 's/^ *open_basedir *=.*$/;\0/' -if /etc/php/php.ini
    - curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/bin
    - composer install
    - php bin/test.php storage/nginx.law.php commit
    - sleep 5 # allow nginx to settle down
    - diff <(curl -Ss http://localhost/) <(echo -n "success:order")
