language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly
install:
    - travis_retry composer update
after_install:
    - php bin/test.php storage/nginx.law.php commit
    - curl http://localhost/
