order-dossier:
  - \Eater\Order\Paper\Order
  - \Eater\Order\Paper\Facter
order-package-provider:
  xbps:
    binary: xbps-install
    class: \Eater\Order\Util\PackageProvider\Xbps
  aptget:
    binary: apt-get
    class: \Eater\Order\Util\PackageProvider\AptGet
  pkgng:
    os:
      - freebsd
    class: \Eater\Order\Util\PackageProvider\Pkgng
  emerge:
    binary: emerge
    class: \Eater\Order\Util\PackageProvider\Emerge
order-service-provider:
  systemd:
    binary: systemd
    class: \Eater\Order\Util\ServiceProvider\Systemd
  runit:
    binary: runit
    class: \Eater\Order\Util\ServiceProvider\Runit
  openrc:
    binary: rc-config
    class: \Eater\Order\Util\ServiceProvider\OpenRC
  debian:
    binary: update-rc.d
    class: \Eater\Order\Util\ServiceProvider\Debian
  freebsd:
    os:
      - freebsd
    class: \Eater\Order\Util\ServiceProvider\FreeBSD
order-user-provider:
  pw:
    os:
      - freebsd
    class: \Eater\Order\Util\UserProvider\Pw
  useradd:
    binary: useradd
    class: \Eater\Order\Util\UserProvider\Useradd
order-include:
  - Law/Wrapped/functions.php
